[project]
name = "pyragix"
version = "0.4.0"
description = "A document ingestion and RAG query system with FAISS indexing and OCR support"
authors = [{name = "psarno", email = "psarno@users.noreply.github.com"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch>=2.9.0",
    "transformers>=4.57.1",
    "sentence-transformers>=5.1.2",
    "huggingface-hub>=0.20.0",
    "tokenizers>=0.22.1",
    "faiss-cpu>=1.12.0",
    "paddleocr>=3.3.0",
    "paddlepaddle>=3.2.0",
    "pillow>=12.0.0",
    "numpy>=2.3.4",
    "requests>=2.32.5",
    "fastapi>=0.120.0",
    "uvicorn[standard]>=0.38.0",
    "beautifulsoup4>=4.14.2",
    "lxml>=6.0.2",
    "psutil>=7.1.2",
    "rank-bm25>=0.2.2",
    "sqlite-utils>=3.38",
    "pymupdf>=1.26.5",
    "langchain-text-splitters>=1.0.0",
    "pydantic>=2.12.3",
    "types-requests>=2.32.4.20250913",
    "scikit-learn>=1.7.2",
    "umap-learn>=0.5.9",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]

[project.urls]
Homepage = "https://github.com/psarno/PyRagix"
Repository = "https://github.com/psarno/PyRagix"
Issues = "https://github.com/psarno/PyRagix/issues"

[project.scripts]
pyragix-ingest = "ingest_folder:main"
pyragix-query = "query_rag:main"
pyragix-web = "web_server:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
dev = [
    "ruff>=0.14.2",
    "pytest>=8.4.2",
    "twine",
    "build",
    "pyright>=1.1.407"
]

[tool.setuptools]
py-modules = ["ingest_folder", "query_rag", "web_server", "config"]
packages = ["classes"]
