"""Type stubs for sqlite_utils."""

from typing import Any, Iterator, Sequence
from pathlib import Path

class Cursor:
    """SQLite cursor wrapper."""

    def execute(self, sql: str, parameters: Sequence[Any] | dict[str, Any] | None = None) -> Cursor: ...
    def fetchone(self) -> tuple[Any, ...] | None: ...
    def fetchall(self) -> list[tuple[Any, ...]]: ...

class Table:
    """SQLite table wrapper."""

    def rows(self) -> Iterator[dict[str, Any]]: ...
    def insert(self, record: dict[str, Any]) -> None: ...
    def insert_all(self, records: Sequence[dict[str, Any]]) -> None: ...
    def create(self, columns: dict[str, type] | None = None, pk: str | None = None) -> None: ...
    def create_index(self, columns: Sequence[str]) -> None: ...

class Database:
    """SQLite database wrapper."""

    def __init__(self, path: str | Path) -> None: ...
    def __getitem__(self, table_name: str) -> Table: ...
    def table_names(self) -> list[str]: ...
    def execute(self, sql: str, parameters: Sequence[Any] | dict[str, Any] | None = None) -> Cursor: ...
