from typing import Any, Callable, Protocol, TypeVar, overload

_T = TypeVar("_T", covariant=True)

class MonkeyPatch:
    @overload
    def setattr(self, target: object, name: str, value: object) -> None: ...
    @overload
    def setattr(self, target: str, value: object, raising: bool = ...) -> None: ...
    def setenv(self, name: str, value: str, *, prepend: bool = ...) -> None: ...
    def delattr(
        self, target: str | object, name: str | object, raising: bool = ...
    ) -> None: ...
    def undo(self) -> None: ...

class CaptureResult(Protocol[_T]):
    @property
    def out(self) -> _T: ...
    @property
    def err(self) -> _T: ...

class CaptureFixture(Protocol[_T]):
    def read(self) -> _T: ...
    def readouterr(self) -> CaptureResult[_T]: ...
    def flush(self) -> None: ...

def fixture(func: Callable[..., _T]) -> Callable[..., _T]: ...
@overload
def raises(expected_exception: type[BaseException]) -> Any: ...
@overload
def raises(expected_exception: type[BaseException], match: str) -> Any: ...
def raises(*args: Any, **kwargs: Any) -> Any: ...
def mark(*args: Any, **kwargs: Any) -> Any: ...
