from typing import Any, Callable, Iterable, Protocol, TypeVar, overload, Generic

_T = TypeVar("_T")

class MonkeyPatch:
    @overload
    def setattr(self, target: object, name: str, value: object) -> None: ...
    @overload
    def setattr(self, target: str, value: object, raising: bool = ...) -> None: ...

    def setenv(self, name: str, value: str, *, prepend: bool = ...) -> None: ...
    def delattr(self, target: str | object, name: str | object, raising: bool = ...) -> None: ...
    def undo(self) -> None: ...

class CaptureResult(Protocol):
    out: str
    err: str

class CaptureFixture(Protocol[_T], Generic[_T]):
    def read(self) -> str: ...
    def readouterr(self) -> CaptureResult: ...
    def flush(self) -> None: ...

def fixture(func: Callable[..., _T]) -> Callable[..., _T]: ...

@overload
def raises(expected_exception: type[BaseException]) -> Any: ...

@overload
def raises(expected_exception: type[BaseException], match: str) -> Any: ...

def raises(*args: Any, **kwargs: Any) -> Any: ...

def mark(*args: Any, **kwargs: Any) -> Any: ...
